name: drivewise
description: Gamified safe driving app.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  geolocator: ^10.1.0
  flutter_background_geolocation: ^4.12.0
  sensors_plus: ^4.0.0
  haptic_feedback: ^1.0.0
  flutter_local_notifications: ^16.3.0
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
